name: Validate with hassfest and HACS

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: home-assistant/actions/hassfest@master
      - uses: hacs/action@main
        with:
          category: integration
          ignore: integration_manifest
